@startuml
actor "Node Operator" as U
participant "Host" as H
participant "Node" as N
participant "GUI" as G
database "Blockchain" as B

== Open Application ==
U -> H : Launch Process
activate H
H -> N : Launch Sub-Process
activate N
N -> G : Launch Sub-Process
activate G
G --> N : ready
deactivate G
N --> H : ready
deactivate N
H --> U : ready
deactivate H

== Exit Application ==
U -> G : Exit
activate G
G -> N: Request Terminate
deactivate G
activate N
N -> G : Terminate Process
activate G
destroy G
N -> N : Shutdown Sequence
N -> H : Request Terminate
deactivate N
activate H
H -> N : Terminate Process
activate N
destroy N
H -> H : Terminate Process
destroy H
H --> U : completed

== Upgrade Application ==
B --> N : Upgrade trigger (HAP)
note over B
  The HAP file to deploy (and block number to deploy on)
  is determined by an arbitrary consensus mechanism
  implemented in the blockchain. The content of the HAP
  file is distributed via a content netowrk coupled with
  the blockchain network. 
end note
activate N
N -> G : Terminate Process
activate G
destroy G
N -> N : Shutdown Sequence
N -> H : Request Terminate
deactivate N
activate H
H -> N : Terminate Process
activate N
destroy N
H -> H : Copy HAP to Archives
H -> N : Delete Directory
H -> G : Delete Directory
H -> N : Deploy HAP Node to Directory
H -> G : Deploy HAP GUI to Directory
H -> N : Launch Sub-Process
activate N
N -> G : Launch Sub-Process
activate G
G --> N : ready
deactivate G
N --> H : ready
deactivate N
deactivate H

== Ping Node ==
H -> N : Ping
activate N
N -> H : Pong
deactivate N

== Ping GUI ==
N -> G : Ping
activate G
G -> N : Pong
deactivate G
@enduml