//-----------------------------------------------------------------------
// <copyright file="UIWebImageViewController.xib.designer.cs" company="Sphere 10 Software">
//
// Copyright (c) Sphere 10 Software. All rights reserved. (http://www.sphere10.com)
//
// Distributed under the MIT software license, see the accompanying file
// LICENSE or visit http://www.opensource.org/licenses/mit-license.php.
//
// <author>Herman Schoenfeld</author>
// <date>2018</date>
// </copyright>
//-----------------------------------------------------------------------

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hydrogen.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("UIWebImageViewController")]
	public partial class UIWebImageViewController {
		
		private UIKit.UIView __mt_view;
		
		private UIWebImageView __mt_uiWebImageView;
		
		#pragma warning disable 0169
		[Foundation.Export("onNextImage:")]
		partial void onNextImage (UIKit.UIButton sender);

		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("uiWebImageView")]
		private UIWebImageView uiWebImageView {
			get {
				this.__mt_uiWebImageView = ((UIWebImageView)(this.GetNativeField("uiWebImageView")));
				return this.__mt_uiWebImageView;
			}
			set {
				this.__mt_uiWebImageView = value;
				this.SetNativeField("uiWebImageView", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UIImageView or subclass
	[Foundation.Register("UIWebImageView")]
	public partial class UIWebImageView {
	}
}
